### ISSUE TITLE
Docs are not up to date!

### ISSUE THREAD

**Issue by jomaway** [bernhardfritz/piksel#10]
It seems like the References on the website are not up to date. Things like sprites and animations which could be found in the lib folder are not mentioned. Are there plans to complete the docs?

**Comment by bernhardfritz** [comment]
Hi @jomaway 👋 
Are you referring to the extensions located in https://github.com/bernhardfritz/piksel/tree/master/src/piksel/ext ?
If so, you are right, documentation for extensions is quite lacking.
The rng extension is the only one documented: https://bernhardfritz.github.io/piksel/#/reference/rng
The way I see it, these extensions are nice to have but are not essential for the general use of piksel.
piksel's API is oriented towards users familiar with e.g. [processing](https://processing.org/) (Java) or [p5.js](https://p5js.org/) (JavaScript).
The stuff in `ext` does not strictly follow the way processing/p5.js handle things but I decided to include it anyways as these extensions cover quite common usecases imho.
Feel free to browse source code of https://github.com/bernhardfritz/mariobreaksout where I extensively made use of sprites, animations and such.
