### ISSUE TITLE
problem loading and displaying true-type fonts

### ISSUE THREAD

**Issue by desalema70** [bernhardfritz/piksel#14]
Hello,

I found a small issue in src/piksel/font.cpp that prevents the library from drawing text that uses a loaded true-type font. The line:

    stbtt_GetFontBoundingBox(info, &x0, &y1, &x1, &y1);

is the issue: the first &y1 should be changed to &y0. With that small fix, everything works fine.

Just thought I'd let you know.

**Comment by bernhardfritz** [comment]
Good find! It has been fixed in #15. Thanks for reporting this.
