### ISSUE TITLE
Graphics::triangle

### ISSUE THREAD

**Issue by francofusco** [bernhardfritz/piksel#4]
I found an issue related to `Graphics::triangle`. When I run the following minimal app:
```c++
#include <piksel/baseapp.hpp>

class App : public piksel::BaseApp {
public:
  // Builds a default environment
  App() : piksel::BaseApp(400, 400, "triangle") {}

  void draw(piksel::Graphics& g) override {
    g.background(glm::vec4(1,1,1,1));
    g.triangle(
      .1*width, .1*width,
      .8*width, .3*height,
      .5*width, .9*height
    );
  }
};

int main() {
  App app;
  app.start();
  return 0;
}
```

I get the following result:

![piksel-triangle](https://i.imgur.com/jhvz8ds.png)

It is not a big deal, for now I will just draw three lines as I do not need to fill it! :wink: Thanks in advance and sorry for bothering!

**Comment by bernhardfritz** [comment]
Yeah, the [triangle implementation](https://github.com/bernhardfritz/piksel/blob/7ff8eb0168004f9db336851556e97c1e6328815a/src/piksel/graphics.cpp#L254) is one of which I am the least proud of. Even though you would think it should be the easiest shape, the fact that this library is optimized for rendering quads and allowing to configure outlines (also on fonts which have arbitrary shapes) suddenly made it unnecessarily tricky to efficiently render triangles with configurable vertices 😛.

The way it is currently implemented, a quad is displayed, that has a triangle texture applied to it, that is skewed in a way to match the points given as parameter to Graphics::triangle.

As a temporary workaround, you could call `g.strokeWeight(0.1f);` before rendering the triangle, then it should look a little bit better.

**Comment by francofusco** [comment]
> As a temporary workaround, you could call g.strokeWeight(0.1f); before rendering the triangle, then it should look a little bit better.

That did it, thank you!
