### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by Joe23232** [bernhardfritz/piksel#8]
Is the project still alive?

**Comment by jomaway** [comment]
Ask myself the same today?

**Comment by bernhardfritz** [comment]
If at all possible, please use https://gitter.im/every-piksel-counts/Lobby for general questions.
But to answer your question, the project is alive in that I am willing to review and merge PRs, but I am not actively contributing new features to it anymore.

**Comment by Joe23232** [comment]
Cool, thanks :)
